# Generated by Django 4.0.5 on 2022-07-03 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.reason'),
        ),
    ]
