# Generated by Django 4.0.5 on 2022-07-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_contactdata_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='confirm_password',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='full_name',
            new_name='username',
        ),
    ]
